[package]
name = 'bmake'
slug = 'bmake'
version = '0.1.0'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = 'A Bash-based Make alternative'

[run]
dependencies = []
sourceDirs = []
builtinDirs = []
binDirs = ['pkg/bin']
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]

[run.shoptOptions]
